cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'casperjs'
brew 'cmake'
brew 'coreutils'
brew 'crystal-lang'
brew 'ffmpeg'
brew 'ical-buddy'
brew 'imagemagick'
brew 'lame'
brew 'openssl'
brew 'phantomjs'
brew 'python'
brew 'rbenv'
brew 'readline'
brew 'ruby-build'
brew 'sudolikeaboss'
brew 'switchaudio-osx'
brew 'tmux'
brew 'valgrind'
brew 'wget'

# cask '1password'
# cask 'adium'
# cask 'atom'
# cask 'firefox'
# cask 'garmin-express'
# cask 'google-chrome'
# cask 'handbrake'
# cask 'mapbox-studio'
# cask 'seashore'
# cask 'slack'
# cask 'steam'
# cask 'transmission'
# cask 'tunnelbear'
# cask 'vlc'
