alias d='docker $*'
alias d-c='LOCALIP=$(localip) docker-compose $*'
alias dap='d-c exec app $*'
alias dps='docker ps -a'
alias dclock='/usr/local/bin/docker run --rm --privileged alpine hwclock -s'
alias ddown='f() { docker ps -aq --filter="name=$1" | xargs docker stop | xargs docker rm };f'
